Replace 'Maximize space' with 'Debloat the OS' step
Replaced 'Maximize space' step with 'Debloat the OS' step to clean up unnecessary packages and free up space during the build process.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -91,15 +91,98 @@ jobs:
                 echo "--- All link-related workflow options seem to be valid! ---"
             fi
 
-              - name: Maximize space
-                uses: easimon/maximize-build-space@master
-        
-       
-            - name: Install deps
+             - name: 'Debloat the OS'
               run: |
-                  sudo apt-get update
-                  sudo apt-get install -y git repo bc bison flex libssl-dev \
-                    libelf-dev pahole build-essential python3 unzip zip curl
+                export DEBIAN_FRONTEND=noninteractive
+                echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
+    
+                echo "Storage spaces before debloat/clean-up:"
+                df -h
+    
+                sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
+                sudo docker image prune --all --force
+                echo "some directories deleted"
+    
+                # Remove large unwanted packages
+                sudo apt-get purge -y \
+                    aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+                    esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+                    google-cloud-sdk imagemagick \
+                    libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+                    mercurial apt-transport-https mono-complete libmysqlclient \
+                    unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+                    libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+                    snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+                    sphinxsearch subversion mongodb-org microsoft-edge-stable || true
+    
+                # Regex-based purges (for bulk families like mysql, php, dotnet)
+                sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
+    
+                # Clean up
+                sudo apt-get autoremove -y
+                sudo apt-get autoclean -y
+                echo "some packages purged"
+    
+                echo "Storage spaces after debloat/clean-up:"
+                df -h
+    
+            - name: 'Setup dependencies and environment'
+              run: |
+                # Setup package sources and apt
+                sudo cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources~
+                sudo sed -Ei 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
+                sudo apt-get update -y
+    
+                # Install kernel build dependencies
+                sudo apt build-dep -y linux
+    
+                # Install clang and LLVM
+                LATEST_LLVM_TOOLCHAIN=$(curl -sSf https://api.github.com/repos/llvm/llvm-project/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep -wi "Linux-X64.tar.xz"$)
+                wget $LATEST_LLVM_TOOLCHAIN -O ./LLVM-latest-Linux-X64.tar.xz
+                tar --wildcards -xvpf ./LLVM-latest-Linux-X64.tar.xz --warning=no-file-changed --ignore-failed-read || true
+                rm -rf *.tar.xz
+    
+                # Install GCC for aarch64 and arm(32)
+                wget https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
+                for file in *.tar.xz; do tar --wildcards -xvpf $file --warning=no-file-changed --ignore-failed-read || true; done
+                rm -rf *.tar.xz
+    
+                # Install some general dependencies
+                sudo apt-get install -y p7zip-full tar bzip2 unrar gzip zip unzip python3-dev repo
+    
+                # Download and extract compiler toolchain
+                extract ()
+                {
+                if [ -f $1 ] ; then
+                    case $1 in
+                    *.tar.bz2)   tar xjf $1   ;;
+                    *.tar.gz)    tar xzf $1   ;;
+                    *.bz2)       bunzip2 $1   ;;
+                    *.rar)       unrar x $1   ;;
+                    *.gz)        gunzip $1    ;;
+                    *.tar)       tar xf $1    ;;
+                    *.tbz2)      tar xjf $1   ;;
+                    *.tgz)       tar xzf $1   ;;
+                    *.zip)       unzip $1     ;;
+                    *.Z)         uncompress $1;;
+                    *.7z)        7z x $1      ;;
+                    *.deb)       ar x $1      ;;
+                    *.tar.xz)    tar xf $1    ;;
+                    *)           echo "'$1' cannot be extracted via extract()" ;;
+                    esac
+                else
+                    echo "'$1' is not a valid file"
+                fi
+                }
+    
+                if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
+                    mkdir ./compiler-toolchain/
+                    wget ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} -P ./compiler-toolchain/
+    
+                    cd ./compiler-toolchain/
+                    extract ./*
+                    cd ../
+                fi
 
                     # Compile and install coccinelle
                     sudo apt-get build-dep -y coccinelle
